### ISSUE TITLE
개발일지에서 링크를 클릭하고 뒤로가기를 하면 404에러가 뜹니다.

### ISSUE THREAD

**Issue by shinsunyoung** [wisemuji/present-web#2]
안녕하세요 wisemuji님! 😏
이슈를 찾아서 올리게 되었습니다!
다름이 아니라 개발일지에서 링크를 클릭하고 뒤로가기를 누르면 계속 404 에러가 뜹니다 ㅜㅜ
하루빨리 고쳐주세요! 🤯

**Comment by wisemuji** [comment]
고쳤습니다 Fresh님! 👍 
도움을 주셔서 감사합니당~~~~~~~~~~~~~~
