### ISSUE TITLE
이메일이 안보내집니다

### ISSUE THREAD

**Issue by shinsunyoung** [wisemuji/present-web#3]
안녕하세요 wisemuji님! 😁
할말을 하고 싶어서 이메일 보내기 버튼을 누르고 양식까지 다 채웠는데
이메일이 안 보내집니다 -_-
하루빨리 고쳐주세요! 🤨

**Comment by wisemuji** [comment]
드디어 이메일 구현을 완료하였습니다 😆
자세한 코드는 [여기](https://github.com/wisemuji/present-web-server)를 확인해쥬세욥👩‍💻
